# Generated by Django 3.2.18 on 2023-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тэга.Используйте только кириллицу, цифры, дефисы и знаки подчёркивания.', max_length=200, unique=True, verbose_name='Тэг')),
                ('slug', models.SlugField(help_text='Укажите уникальный адрес тэга.Используйте только латиницу, цифры, дефисы и знаки подчёркивания.', max_length=200, unique=True, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Здесь можно загрузить картинку, объёмом не более 5Мб.', upload_to='static/gallery/', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки изображения')),
                ('tags', models.ManyToManyField(help_text='Введите id ассоциирующегося тега.', related_name='gallery', to='gallery.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('-pub_date',),
            },
        ),
    ]
