# Generated by Django 3.2.18 on 2023-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='discount',
            field=models.IntegerField(default='10', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(default='2023-12-31 22:22:22', help_text='Введите дату и время окончания акции\n        в формате 2022-02-22 22:22:22.', verbose_name='Дата и время окончания акции'),
        ),
    ]
