# Generated by Django 2.2.16 on 2023-06-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_action', '0002_auto_20230604_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-date'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Введите дату и время окончания акции\n        в формате 2022-02-22 22:22:22.', verbose_name='Дата и время окончания акции'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
